version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building project..."
      - npm run build || echo "No build script found, skipping build"

artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
    - src/**/*
    - routes/**/*
  base-directory: .
  discard-paths: no
